[package]
name = "publicviewing-cli"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wry = "0.35.2"
tao = "0.23"
clap = { version = "4.4.18", features = ["derive"] }
instant = "0.1.12"
