name: Check fmt

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'

jobs:
  clippy_fmt_check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: install stable
        uses: dtolnay/rust-toolchain@stable
      - name: fmt
        run: cargo fmt --all -- --check
